trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

variables:
  group: 'pipelines'

stages:
- stage: Preflight
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm i
      displayName: 'Install dependencies'
    - script: |
        npm run standard
      displayName: 'Standardjs report'
- stage: Test
  jobs:
  - job: Node_8
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
  - job: Node_10
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
  - job: Node_12
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
