trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

variables:
  group: 'pipelines'

stages:
- stage: Build
  jobs:
  - job: Pre-flight checks
    steps:
    # When we are ready to enforce standardjs, remove redirection and remove '|| true' from the standard script in package.json
    - script: |
        npm run standard
      displayName: 'Standardjs report'
- stage: Test
  jobs:
  - job: Node 8
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
  - job: Node 10
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
  - job: Node 12
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - template: azure-templates/test.template.yml
